import Joi from "joi";

export const verifiedAssetSchema = Joi.object({
  majorCategory: Joi.string().optional(),
  majorCategoryDescription: Joi.string().optional(),
  minorCategory: Joi.string().optional(),
  minorCategoryDescription: Joi.string().optional(),
  tagNumber: Joi.string().optional(),
  serialNumber: Joi.string().optional(),
  assetDescription: Joi.string().optional(),
  assetType: Joi.string().optional(),
  assetCondition: Joi.string().optional(),
  country: Joi.string().optional(),
  region: Joi.string().optional(),
  cityName: Joi.string().optional(),
  dao: Joi.string().optional(),
  daoName: Joi.string().optional(),
  businessUnit: Joi.string().optional(),
  buildingNo: Joi.string().optional(),
  floorNo: Joi.string().optional(),
  employeeId: Joi.string().optional(),
  poNumber: Joi.string().optional(),
  poDate: Joi.string().optional(),
  deliveryNoteNo: Joi.string().optional(),
  supplier: Joi.string().optional(),
  invoiceNo: Joi.string().optional(),
  invoiceDate: Joi.string().optional(),
  modelOfAsset: Joi.string().optional(),
  manufacturer: Joi.string().optional(),
  ownership: Joi.string().optional(),
  bought: Joi.string().optional(),
  terminalId: Joi.string().optional(),
  atmNumber: Joi.string().optional(),
  locationTag: Joi.string().optional(),
  buildingName: Joi.string().optional(),
  buildingAddress: Joi.string().optional(),
  userLoginId: Joi.string().optional(),
  mainSubSeriesNo: Joi.number().integer().optional(),
  assetDateCaptured: Joi.string().optional(),
  assetTimeCaptured: Joi.string().optional(),
  assetDateScanned: Joi.string().optional(),
  assetTimeScanned: Joi.string().optional(),
  qty: Joi.number().integer().min(1).optional(),
  phoneExtNo: Joi.string().optional(),
  fullLocationDetails: Joi.string().optional(),
  journalRefNo: Joi.string().optional(),
  images: Joi.string().optional(),
});
